services:
  - type: web
    name: poker-ultra
    plan: free
    env: node
    region: singapore
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: node server/dist/index.js
    healthCheckPath: /api/rooms
    envVars:
      - key: NODE_ENV
        value: production
