services:
  - type: web
    name: poker-ultra
    plan: standard
    env: node
    region: oregon
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - poker-ultra.onrender.com
